version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kalunge
      POSTGRES_PASSWORD: demo_password
      POSTGRES_DB: kotlin_demo_db
    ports:
      - "5432:5432"


