version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kalunge
      POSTGRES_PASSWORD: demo_password
      POSTGRES_DB: kotlin_demo_db
    ports:
      - "5432:5432"
  kotlinapp:
    container_name: kotlinapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/kotlin_demo_db
      PG_USER: kalunge
      PG_PASSWORD: demo_password
    depends_on:
      - postgres
