spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin_demo_db
    username: kalunge
    password: demo_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: demo