spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kotlin_demo_db}
    username: ${PG_USER:kalunge}
    password: ${PG_PASSWORD:demo_password}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: demo
